### ISSUE TITLE
Ruby 1.9 compatibility

### ISSUE THREAD

**Issue by ghost** [relevance/log_buddy#1]
[original LH ticket](http://relevance.lighthouseapp.com/projects/19074/tickets/3)

 This ticket has 0 attachment(s).

**Comment by ghost** [comment]
**Ruby 1.9 compatibility**

sounds like echoe blows up hard with 1.9

 by Rob Sanheim

**Comment by ghost** [comment]
**Ruby 1.9 compatibility**

 by Rob Sanheim

**Comment by ghost** [comment]
**Ruby 1.9 compatibility**

 by Rob Sanheim

**Comment by spicycode** [comment]
The only issue I see with this remaining is the Gem logger which fails on 1.9

**Comment by spicycode** [comment]
Triaging for Ruby 1.9 (Closed by 31089d9e59baf19b306725209ee1bef80762a9c5)
