### ISSUE TITLE
LogBuddy clobbers rails script/generate when running Ruby 1.9

### ISSUE THREAD

**Issue by rubyredrick** [relevance/log_buddy#4]
WIth logbuddy required in the environment, and when running Ruby 1.9.1

$ script/generate model foo
undefined method `exists' for #ActiveSupport::BufferedLogger:0x0000010221ea38

The Object#logger method added by LogBuddy is confusing the Rails generate command which uses logger as the name of the object which interacts with the project's files, not the normal use of the word, but it is what it is.

I ran this under the debugger today, and confirmed that the generator is somehow getting the looger from logbuddy.

**Comment by TylerRick** [comment]
Thank you for reporting this. That saved me from hours of debugging this on my own.

I don't know how you ended up working around it, but I just changed by config.gem line to this:

<pre>
config.gem 'relevance-log_buddy', :lib => 'log_buddy', :source => 'http://gems.github.com' unless $0 =~ %r(script/generate)
</pre>
